### ISSUE TITLE
ERROR: AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access

### ISSUE THREAD

**Issue by mpjbusiness** [fathym/eac#8]
**An error was experienced when trying to run the following command in VS:** 
fathym eac env clouds azure define -g

**Error:** 
AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access

**Resolution:**
The following commands needed to be run to re-auth Azure
az account clear
az login

**Proposed solution to automate resolution:**
Look for that error in the CLI, and run the clear login automatically

**Comment by mcgear** [comment]
Was able to get this recreated locally, working on a command that will allow us to check valid, and reissue login if necessary

**Comment by mcgear** [comment]
This is now handled in the rbac creation flow specifically

**Comment by mcgear** [comment]
Deployment complete in manual deploy 0.0.180

**Comment by mcgear** [comment]
Deployment complete in manual deploy 0.0.180
